signatech.models {
  basePath = "models"

  pose = "pose/handpose.onnx"
  signRecognition = "sign/sign-recognition.onnx"
  translation = "translation/gloss-to-text.onnx"
}

signatech.onnx {
  preferCuda = true
}
